name: Build Android
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build && npm run export
      - run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "MiniFortnite" "com.yourname.minifortnite" --web-dir=out
          npx cap add android
          npx cap copy
      - run: cd android && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v3
        with:
          name: MiniFortnite-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
